### PR TITLE
Two separate updates to ImageCache class.

### PR DESCRIPTION
**Pull request by eschlenz**
Hey Steve,

I have made two commits that I would like you to consider pulling in. 

The first commit simply opens up access to the CompressFormat and quality via setters. This is fundamentally what I needed, but it might be nice in the future to allow such options to be associated with each image request job.

The second commit implements the cancelAll, and introduces a cancel(id). The cancelAll implementation should prevent any queued jobs from running. Unfortunately, any currently running jobs will still finish execution. This is mainly due to the fact that halting of IO data is not possible in its current state, due to the delegation of the work from the Runnable to getImage(). In the future it would be good to make the job truly interruptible (ie: kill IO). A job that finishes execution, but was cancelled, will not fire a message to the handler. This should eliminate issues with notifications on cancelled jobs.

I hope to contribute more soon, and hope you can incorporate these changes!

P.S. Sorry this work was not done in a topic branch. This is the first time I've done this, and missed that part of the guide until after the commits were performed.

Eric

### CODE REVIEW

**Comment by eschlenz** [comment]
I have also updated the support library to the latest version. And included an Android build.xml, which is useful for those using Jenkins/Hudson to build their apps outside of eclipse. Cheers.

**Comment by xxv** [comment]
Patches look great. Interactive and unit tests pass.

**Comment by xxv** [comment]
Thanks for your contributions!

**Comment by eschlenz** [comment]
Awesome. Thanks!
Eric

Date: Thu, 27 Sep 2012 14:02:09 -0700

**Pull request merged**
